export const errors = {
  NOT_FOUND: "NOT_FOUND",
  INVALID_ARG: "INVALID_ARG",
  NOT_LOGGED_IN: "NOT_LOGGED_IN",
  UNAUTHORIZED: "UNAUTHORIZED",
  DATABASE_ERROR: "DATABASE_ERROR",
  INVALID_TOKEN: "INVALID_TOKEN",
};
